---
title: "Lecture 3 Notes - Cognitive Load, Clutter, Preattentive Attributes"
author: "Jeremy Morris"
affiliation-title: "University of Utah"
date: last-modified
title-block-style: default
title-block-banner: true
format: 
  html:
      embed-resources: true
      theme: flatly
      code-block-bg: true
      code-block-border-left: "#31BAE9"
      highlight-style: printing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

# Quiz 3 Review

## Lecture 3 - Eliminate Clutter
* Include only what adds to the audience’s understanding, remove everything else
* Every element added increases cognitive load
* Clutter = elements that take up space/use ink but do not increase understanding
* Data-ink: non-erasable ink used for the presentation of data (i.e. if any of the data-ink is removed, the graphic would lose content)
    * Data-ink ratio = Data-ink / total ink used to print graphic
    * The data-ink ratio represents the proportion of the graphics ink devoted to the non-redundant display of data/information
* Gestalt principles: principles of visual perception that define how people interact with and create order out of visual stimuli
    * They aim to formulate the regularities according to which the perceptual input is organized into unitary forms, also referred to as (sub)wholes, groups, groupings, or Gestalten (the plural form of Gestalt)
    * Your brain filling in the gaps
* Gestalt Principles
    * Proximity
        * elements tend to be perceived as aggregated into groups if they are near each other
        * strongest principle
    * Similarity
        * elements tend to be integrated into groups if they are similar to each other
    * Enclosure
        * elements tend to be integrated into groups if they are within an enclosure
        * used to override other Gestalts
    * Closure
        * The closure principle means that people like things to be simple and to fit inside known constructs. 
        * Because of this, we tend to see a set of individual elements as as single, recognizable shape when we can.
        * When pieces of a whole are missing, we fill in the missing pieces.
        * Many charting tools include borders or shading.
        * The Closure principle tells us that these are very likely unnecessary.
    * Continuity
        * Continuity is similar to closure: when looking at objects, our eyes seek the smoothest path and naturally create continuity in what we see, even where it might not exist.
        * The continuity principle is why we can often eliminate some chart elements like axes lines.
    * Connection
        * elements tend to be grouped together if they are connected
        * can also override other Gestalts
* Lack of Visual Order
    * When design is thoughtful, it fades into the background so that your audience doesn’t even notice it.
    * When its not, however, your audience feels the burden.
    * Create clean horizontal and vertical lines in the design
    * Without visual cues, your audience will read in a “Z” pattern, starting in the top left, moving to the right and down.
    * Avoid diagonal components including lines and text
    * E.g. people read text rotated at 45 degrees ~50% slower than normal text
        * 90 degree text will be read over 200% slower
    * White space is blank space on the page.
        * Blank space should never be filled “just because”
        * Remember that every additional element on a chart takes cognitive load to process, so white space helps focus your audience.
        * Guidelines
            * Margins should remain free of text and visuals
            * Resist the urge to stretch visuals to take up the available space
            * If there is only one really important thing, think about making that the only thing on your slide
        * Whitespace means no non-data-ink
    * Strategic use of contrast
        * Do not include too many contrasting elements
        * Use color intentionally to draw attention and to group things together
        * Use grey scale to de-emphasize but still leave elements on the chart for context
        * Consider removing numeric values if they don't add to the message
        * Remove portions of the chart scafolding when they are not necessary

## Lecture 4 – Directing the Audience

* Preattentive attributes introduction
    * The primary goal of data visualization is to make it easier to see patterns and trends
    * How do we do that?
        * Remove clutter
        * Focus attention
* Memory review
    * Sensory (or Iconic) Memory 
        * Holds information for a fraction of a second
        * Tuned to a set of preattentive attributes
    * Short-term (or Working) memory
        * People can keep about four chunks of visual information in their short-term memory
    * Long-term memory
        * Aggregate of visual and verbal memory, which work differently
        * Images can help us recall things quicker
    * Studies show that we have 3-8 seconds before audiences decide whether they will continue looking at a piece of content.
* Preattentive attributes enable our audience to see what we want them to see before they even know they’re seeing it!
* Preattentive attribute notes
    * These are all the preattentive attributes
        * Orientation
        * Shape
        * Line length
        * Line width
        * Size
        * Curvature
        * Added marks
        * Enclosure
        * Hue
        * Intensity
        * Spatial position
        * Motion
    * Note that people tend to associate quantitative values for some (but not all) preattentive attributes
    * Preattentive attributes are used for:
        * Drawing your audience’s attention
        * Creating a visual hierarchy of information
* Preattentive attributes in text
    * Bold
    * Color
    * Italics
    * Size
    * Separate spatially (add whitespace)
    * Online/enclosure
    * Underline/added marks
* Preattentive attributes in charts
    * without preattentive attributes, your audience needs to search for the insights in your charts
    * this could be good if that's what you want. most often, it isn't.
    * use color to draw attention and make a point.
    * only add multiple colors if you have multiple points
    * do not use color just for the sake of using color
    * you can repeat the same chart with multiple treatments. this could be a good way to lead your audience through a story.
    * labels can add clutter if there are too many of them
    * think about strategically using labels on charts
* Strategic Preattentive Attributes
    * Size, color, page placement
    * Size
        * Relative size denotes relative importance
        * This is especially true when you have multiple visualizations displayed at once
        * Make sure you use size intentionally, otherwise your audience will not focus where you want them to.
        * Size is also why certain chart types work so well. bubble plots, for example.
    * Color
        * use sparingly
        * too many colors are distracting and lose preattentive value
        * switch to saturation/instensity if you need something related to a quantitative value
        * always use color intentionally. 
            * do not use color just to have color. 
            * it will be confusing to your audience
        * Other color notes
            * use color consistently -- Using color consistently means you train your audience to know what to expect. Colors should only change if meaning changes.
            * Design with colorblindness in mind -- Avoid using shades of red and green together. If you need red/green, make sure there’s some other visual indication of difference.
            * Be thoughtful of tone -- Be thoughtful of how the results will be perceived. Softer tones could come across as too “nice”. Bolder tones more aggressive.
            * Brand colors -- In most circumstances, yes. But, brand colors may not have been chosen with data visualizations in mind. When brand colors can’t be used, use standard colors (black, grey) or pick a complementary color.
    * Page placement
        * Without other visual cues, most members of you audience will read in a Z pattern (left to right, top to bottom).
        * Take advantage of this by placing things on the page in this order.
        * Don’t make your audience work too hard (they may not get your point).
        * On a related note, when possible, make sure your charts follow generally acceptable patterns (e.g. negative values on the left, positive on the right).
* Using preattentive attributes
    * Guideline: use preattentive attributes sparingly; too many reduces focus for the audience
    * Process steps:
        * Start with everything "untreated"
        * "Treat" aspects of the data visualization one at a time with an effective preattentive attribute (Stop before you add too many "treatments")





## Lab 3 – introduction to ggplot

* ggplot2 is a package created by Hadley Wickam to increase the functionality of plotting in R.
* It is a flexible and extensible way to generate graphics
* Allows the user to programmatically control nearly every element of the chart.
* Two main functions to generate plots
* qplot – create basic charts, can send aesthetic mappings in as parameters
* ggplot – create any chart, need to add various elements one at a time for display
* Main elements of a chart, can be used in combination with one another to generate the desired visualization
* aes() – aesthetic mapping, map data to elements of the chart
* geom – geometrical objects added to layers of the chart. Examples include the following (this list is in no way exhaustive)
* geom_point – scatterplot
* geom_bar – bar chart
* geom_line – line chart
* geom_hline – add a horizontal line
* facets – generates the same plot for different slices of the data. Will cover in lab 4.
* Scales – this set of functions allows the user to control the axes
* Theme – allows the user to control the overall look and feel.